language: objective-c
before_install:
- uname -a
- brew install caskroom/cask/brew-cask
- brew tap caskroom/cask
- brew cask install virtualbox
- VBoxManage --version
install:
- brew install ansible
- gem install vagrant
script:
- wget https://vagrantcloud.com/hashicorp/precise64/version/2/provider/virtualbox.box
- vagrant box add u64 virtualbox.box
- vagrant up
- ansible-playbook playbooks/base.yml -i hosts --list-tasks
- ansible-playbook playbooks/base.yml -i hosts -vvvv
notifications:
  hipchat:
    rooms:
      secure: DDXxlEm+/S+yQS3wGctA2XQ5VlnpQ9r0uHAKeIXajCGQv/oOz5vyYq+pfOOznL0bAqedR5LhVpufyCeeamyQYCfPEvH2/8q7JMZL6ekyrQlOvYUbzWwwoxSwH/gwGKSisa5KYTnoD31UMG4IDfPkKiwRTcaY99cB/WBPwqeq318=
