#!/usr/bin/env bash
set -x
if [ -z ${BUILD_NUMBER} ];then
	echo "please call this using jenkins"
	exit 1
fi
# call from jenkins

if [ x"${vagrant_destroy}" = x"true" ];then
	vagrant destroy -f
fi

# halt and up
vagrant halt -f
vagrant up

# add public key to authorized_keys
sleep 10
./vagrant_root_ssh.sh

# just build
./build

build_status=$?

# run test
./run_test

test_status=$?

if [ x"${vagrant_package}" = x"true" ];then
mkdir boxes
# package and import
vagrant package --output boxes/ansible.ubuntu.base_${BUILD_NUMBER}.box
vagrant box add ansible.ubuntu.base_${BUILD_NUMBER} boxes/ansible.ubuntu.base_${BUILD_NUMBER}.box
fi

# backup jenkins
#jenkins.cli get-job ansible.ubuntu.base > ansible.ubuntu.base.xml

# generate report
#./report

# backup
#git add .
#git commit -a -m "${commit_message}"

# snapshot
git checkout -b HB_${BUILD_NUMBER}
git push origin HEAD

# back to build
#git checkout master

# push master to origin
#git push origin master

exit $test_status
