#!/usr/bin/env bash
set -x
if [ -z ${BUILD_NUMBER} ];then
	echo "please call this using jenkins"
	exit 1
fi
# call from jenkins

if [ x"${vagrant_destroy}" = x"true" ];then
	vagrant destroy -f
fi

# halt and up
vagrant halt -f
vagrant up

# add public key to authorized_keys
sleep 10
./vagrant_root_ssh.sh

# just build
./build

build_status=$?

# run test
./run_test

test_status=$?

# package and import
vagrant package --output ansible.ubuntu.base_${BUILD_NUMBER}.box
vagrant box add ansible.ubuntu.base_${BUILD_NUMBER} ansible.ubuntu.base_${BUILD_NUMBER}.box

# backup jenkins
jenkins.cli get-job ansible.ubuntu.base > ansible.ubuntu.base.xml

# backup
git add .
git commit -a -m "${commit_message}"

# snapshot
git checkout -b build_${BUILD_NUMBER}
git push origin HEAD

# back to master
git checkout master

# push master to origin
git push origin master

if [ $build_status -o $test_status ];then
	exit 1
fi
