---
- hosts: all
  remote_user: root
  pre_tasks:
    - name: test connection
      ping:
    - name: change apt sources
      shell: sed -i 's/us.archive.ubuntu.com/mirrors.sohu.com/g' /etc/apt/sources.list;apt-get update
    - name: add rye libapache2-mod-auth-openid ppa
      apt_repository: repo='ppa:rye/ppa' update_cache=yes
    - name: install apache2
      apt: name=apache2 state=present
    - name: install libapache2-mod-auth-openid
      apt: name=libapache2-mod-auth-openid state=present
    - name: enable apache authopenid module
      shell: a2enmod authopenid
    - name: restart apache2
      service: name=apache2 state=restarted
  roles:
    - Ansibles.build-essential
    - Ansibles.python
  post_tasks:
    - name: Add brightbox ruby repository
      apt_repository: repo='ppa:brightbox/ruby-ng' update_cache=yes
    - name: Install ruby
      apt: name={{ item }} state=latest
      with_items:
        - ruby2.1
        - ruby2.1-dev
    - name: remove rubygems mirror
      shell: gem sources --remove https://rubygems.org/
    - name: remove taobao gem mirror
      shell: gem sources --remove http://ruby.taobao.org/
    - name: add taobao mirror
      shell: gem sources -a http://ruby.taobao.org/
    - name: install cucumber and aruba
      shell: gem install cucumber aruba --no-ri --no-rdoc
    - name: install rdiscount
      shell: gem install rdiscount --no-ri --no-rdoc
    - name: install Pygments
      shell: pip install Pygments
