---
- hosts: all
  remote_user: root
  pre_tasks:
    - name: test connection
      ping: 
    - name: change apt sources
      shell: sed -i 's/us.archive.ubuntu.com/mirrors.sohu.com/g' /etc/apt/sources.list;apt-get update
    - name: Add brightbox ruby repository
      apt_repository: repo='ppa:brightbox/ruby-ng' update_cache=yes
    - name: Install ruby
      apt: name={{ item }} state=latest
      with_items:
        - ruby2.1
        - ruby2.1-dev
    - name: remove rubygems mirror
      shell: gem sources --remove https://rubygems.org/
    - name: remove taobao gem mirror
      shell: gem sources --remove http://ruby.taobao.org/
    - name: add taobao mirror
      shell: gem sources -a http://ruby.taobao.org/
    - name: install cucumber and aruba
      shell: gem install cucumber aruba --no-ri --no-rdoc
