---
- tasks:
  - name: create temporary directory
    shell: mktemp -d
    register: tempdir
    sudo: true
    tags:
      - vagrant

  - name: download vagrant
    get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3_x86_64.deb dest={{ tempdir.stdout }}/vagrant.deb
    tags:
      - vagrant

  - name: install vagrant
    command: dpkg -i {{ tempdir.stdout }}/vagrant.deb
    tags:
      - vagrant

  - name: cleanup temporary directory
    file: name={{ tempdir.stdout }} state=absent
    tags:
      - vagrant